const { T } = require( "../bin/glsltype.js" )

console.log( T.Error.implicitConversions().map( t => t.identifier() ) )
console.log( T.Void.implicitConversions().map( t => t.identifier() ) )
console.log( T.Bool.implicitConversions().map( t => t.identifier() ) )
console.log( T.Int.implicitConversions().map( t => t.identifier() ) )
console.log( T.Uint.implicitConversions().map( t => t.identifier() ) )
console.log( T.Float.implicitConversions().map( t => t.identifier() ) )
console.log( T.Double.implicitConversions().map( t => t.identifier() ) )

console.log( T.Bvec2.implicitConversions().map( t => t.identifier() ) )
console.log( T.Bvec3.implicitConversions().map( t => t.identifier() ) )
console.log( T.Bvec4.implicitConversions().map( t => t.identifier() ) )
console.log( T.Ivec2.implicitConversions().map( t => t.identifier() ) )
console.log( T.Ivec3.implicitConversions().map( t => t.identifier() ) )
console.log( T.Ivec4.implicitConversions().map( t => t.identifier() ) )
console.log( T.Uvec2.implicitConversions().map( t => t.identifier() ) )
console.log( T.Uvec3.implicitConversions().map( t => t.identifier() ) )
console.log( T.Uvec4.implicitConversions().map( t => t.identifier() ) )
console.log( T.Vec2.implicitConversions().map( t => t.identifier() ) )
console.log( T.Vec3.implicitConversions().map( t => t.identifier() ) )
console.log( T.Vec4.implicitConversions().map( t => t.identifier() ) )
console.log( T.Dvec2.implicitConversions().map( t => t.identifier() ) )
console.log( T.Dvec3.implicitConversions().map( t => t.identifier() ) )
console.log( T.Dvec4.implicitConversions().map( t => t.identifier() ) )