const { T } = require( "../bin/glsltype.js" )

console.log( T.Error.identifier(), T.Error.rank(), T.Error.implicitConversions().map( t => t.identifier() ) )
console.log( T.Void.identifier(), T.Void.rank(), T.Void.implicitConversions().map( t => t.identifier() ) )
console.log( T.Bool.identifier(), T.Bool.rank(), T.Bool.implicitConversions().map( t => t.identifier() ) )
console.log( T.Int.identifier(), T.Int.rank(), T.Int.implicitConversions().map( t => t.identifier() ) )
console.log( T.Uint.identifier(), T.Uint.rank(), T.Uint.implicitConversions().map( t => t.identifier() ) )
console.log( T.Float.identifier(), T.Float.rank(), T.Float.implicitConversions().map( t => t.identifier() ) )
console.log( T.Double.identifier(), T.Double.rank(), T.Double.implicitConversions().map( t => t.identifier() ) )

console.log( T.Bvec2.identifier(), T.Bvec2.rank(), T.Bvec2.implicitConversions().map( t => t.identifier() ) )
console.log( T.Bvec3.identifier(), T.Bvec3.rank(), T.Bvec3.implicitConversions().map( t => t.identifier() ) )
console.log( T.Bvec4.identifier(), T.Bvec4.rank(), T.Bvec4.implicitConversions().map( t => t.identifier() ) )
console.log( T.Ivec2.identifier(), T.Ivec2.rank(), T.Ivec2.implicitConversions().map( t => t.identifier() ) )
console.log( T.Ivec3.identifier(), T.Ivec3.rank(), T.Ivec3.implicitConversions().map( t => t.identifier() ) )
console.log( T.Ivec4.identifier(), T.Ivec4.rank(), T.Ivec4.implicitConversions().map( t => t.identifier() ) )
console.log( T.Uvec2.identifier(), T.Uvec2.rank(), T.Uvec2.implicitConversions().map( t => t.identifier() ) )
console.log( T.Uvec3.identifier(), T.Uvec3.rank(), T.Uvec3.implicitConversions().map( t => t.identifier() ) )
console.log( T.Uvec4.identifier(), T.Uvec4.rank(), T.Uvec4.implicitConversions().map( t => t.identifier() ) )
console.log( T.Vec2.identifier(), T.Vec2.rank(), T.Vec2.implicitConversions().map( t => t.identifier() ) )
console.log( T.Vec3.identifier(), T.Vec3.rank(), T.Vec3.implicitConversions().map( t => t.identifier() ) )
console.log( T.Vec4.identifier(), T.Vec4.rank(), T.Vec4.implicitConversions().map( t => t.identifier() ) )
console.log( T.Dvec2.identifier(), T.Dvec2.rank(), T.Dvec2.implicitConversions().map( t => t.identifier() ) )
console.log( T.Dvec3.identifier(), T.Dvec3.rank(), T.Dvec3.implicitConversions().map( t => t.identifier() ) )
console.log( T.Dvec4.identifier(), T.Dvec4.rank(), T.Dvec4.implicitConversions().map( t => t.identifier() ) )

console.log( T.Ivec2.implicitConvertableTo( T.Vec2 ) )